"""initial schema

Revision ID: c05b1e62b197
Revises: 
Create Date: 2026-09-27 13:49:02.899260
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'c05b1e62b197'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.Date(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_sources'))
    )
    op.create_table('normatives',
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('is_editable', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_normatives')),
    sa.UniqueConstraint('code', name='uq_normative_code')
    )
    op.create_index(op.f('ix_normatives_code'), 'normatives', ['code'], unique=False)
    op.create_table('object_types',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_object_types'))
    )
    op.create_index(op.f('ix_object_types_code'), 'object_types', ['code'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vendors',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('website', sa.String(length=1024), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors')),
    sa.UniqueConstraint('name', name='uq_vendor_name')
    )
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=False)
    op.create_table('audit_log',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_log_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('import_batches',
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('source_file', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_import_batches_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches'))
    )
    op.create_index(op.f('ix_import_batches_kind'), 'import_batches', ['kind'], unique=False)
    op.create_table('parameter_groups',
    sa.Column('object_type_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['object_type_id'], ['object_types.id'], name=op.f('fk_parameter_groups_object_type_id_object_types'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parameter_groups')),
    sa.UniqueConstraint('object_type_id', 'code', name='uq_pg_object_code')
    )
    op.create_index(op.f('ix_parameter_groups_object_type_id'), 'parameter_groups', ['object_type_id'], unique=False)
    op.create_table('processes',
    sa.Column('object_type_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metric_code', sa.String(length=64), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['object_type_id'], ['object_types.id'], name=op.f('fk_processes_object_type_id_object_types'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processes')),
    sa.UniqueConstraint('object_type_id', 'code', name='uq_process_object_code')
    )
    op.create_index(op.f('ix_processes_object_type_id'), 'processes', ['object_type_id'], unique=False)
    op.create_table('projects',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('object_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('params_version', sa.String(length=32), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('source_file_name', sa.String(length=512), nullable=True),
    sa.Column('uploaded_file_path', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['object_type_id'], ['object_types.id'], name=op.f('fk_projects_object_type_id_object_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_projects_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_object_type_id'), 'projects', ['object_type_id'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('catalog_versions',
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('solutions_count', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('import_batch_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], name=op.f('fk_catalog_versions_import_batch_id_import_batches'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_versions')),
    sa.UniqueConstraint('version', name=op.f('uq_catalog_versions_version'))
    )
    op.create_table('parameters',
    sa.Column('object_type_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('value_type', sa.String(length=32), nullable=False),
    sa.Column('default_value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('default_text', sa.Text(), nullable=True),
    sa.Column('min_value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('max_value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('data_source_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], name=op.f('fk_parameters_data_source_id_data_sources'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['parameter_groups.id'], name=op.f('fk_parameters_group_id_parameter_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['object_type_id'], ['object_types.id'], name=op.f('fk_parameters_object_type_id_object_types'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parameters')),
    sa.UniqueConstraint('object_type_id', 'code', name='uq_param_object_code')
    )
    op.create_index(op.f('ix_parameters_group_id'), 'parameters', ['group_id'], unique=False)
    op.create_index(op.f('ix_parameters_object_type_id'), 'parameters', ['object_type_id'], unique=False)
    op.create_table('scenarios',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('horizon_years', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('last_calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_scenarios_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenarios'))
    )
    op.create_index(op.f('ix_scenarios_project_id'), 'scenarios', ['project_id'], unique=False)
    op.create_table('solution_types',
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_mobile', sa.Boolean(), nullable=False),
    sa.Column('requires_passage', sa.Boolean(), nullable=False),
    sa.Column('passage_margin_m', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], name=op.f('fk_solution_types_process_id_processes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_solution_types')),
    sa.UniqueConstraint('code', name='uq_solution_type_code')
    )
    op.create_index(op.f('ix_solution_types_process_id'), 'solution_types', ['process_id'], unique=False)
    op.create_table('calculations',
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('catalog_version', sa.String(length=64), nullable=True),
    sa.Column('params_version', sa.String(length=32), nullable=True),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_calculations_scenario_id_scenarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calculations'))
    )
    op.create_index(op.f('ix_calculations_scenario_id'), 'calculations', ['scenario_id'], unique=False)
    op.create_table('simulation_runs',
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('speed_factor', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('kpi', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_simulation_runs_scenario_id_scenarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simulation_runs'))
    )
    op.create_index(op.f('ix_simulation_runs_scenario_id'), 'simulation_runs', ['scenario_id'], unique=False)
    op.create_table('solutions',
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('solution_type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('catalog_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('scenario_label', sa.Text(), nullable=True),
    sa.Column('cases', sa.Text(), nullable=True),
    sa.Column('trl', sa.Integer(), nullable=True),
    sa.Column('market_potential', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('payload_kg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('own_weight_kg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('length_m', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('width_m', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('height_m', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('min_passage_width_m', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('lift_height_m', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('max_speed_mps', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('throughput_per_hour', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('throughput_unit', sa.String(length=32), nullable=True),
    sa.Column('autonomy_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('charge_time_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('positioning_accuracy_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('navigation_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('min_temp_c', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('max_temp_c', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('max_noise_dba', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('max_floor_roughness_mm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('charge_power_kw', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('battery_capacity_kwh', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit_price_rub', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('price_source', sa.String(length=32), nullable=True),
    sa.Column('software_price_rub', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('implementation_price_rub', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('service_rate_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('purchase_model', sa.String(length=32), nullable=False),
    sa.Column('lifetime_years', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('battery_lifetime_years', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('infrastructure_price_rub', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('applicable_object_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('process_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('restrictions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('infrastructure_requirements', sa.Text(), nullable=True),
    sa.Column('airside_certified', sa.Boolean(), nullable=True),
    sa.Column('medical_sanitation_ready', sa.Boolean(), nullable=True),
    sa.Column('data_source_id', sa.Uuid(), nullable=True),
    sa.Column('specs_updated_at', sa.Date(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('completeness', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_variant_of_id', sa.Uuid(), nullable=True),
    sa.Column('variant_label', sa.String(length=128), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], name=op.f('fk_solutions_data_source_id_data_sources'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['is_variant_of_id'], ['solutions.id'], name=op.f('fk_solutions_is_variant_of_id_solutions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['solution_type_id'], ['solution_types.id'], name=op.f('fk_solutions_solution_type_id_solution_types'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_solutions_vendor_id_vendors'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_solutions'))
    )
    op.create_index(op.f('ix_solutions_catalog_id'), 'solutions', ['catalog_id'], unique=False)
    op.create_index(op.f('ix_solutions_industry'), 'solutions', ['industry'], unique=False)
    op.create_index(op.f('ix_solutions_solution_type_id'), 'solutions', ['solution_type_id'], unique=False)
    op.create_index(op.f('ix_solutions_status'), 'solutions', ['status'], unique=False)
    op.create_index(op.f('ix_solutions_vendor_id'), 'solutions', ['vendor_id'], unique=False)
    op.create_table('project_solutions',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('solution_id', sa.Uuid(), nullable=False),
    sa.Column('added_manually', sa.Boolean(), nullable=False),
    sa.Column('warning', sa.Text(), nullable=True),
    sa.Column('match_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('match_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_solutions_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], name=op.f('fk_project_solutions_solution_id_solutions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_solutions')),
    sa.UniqueConstraint('project_id', 'solution_id', name='uq_project_solution')
    )
    op.create_index(op.f('ix_project_solutions_project_id'), 'project_solutions', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_solutions_solution_id'), 'project_solutions', ['solution_id'], unique=False)
    op.create_table('scenario_solutions',
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('solution_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_scenario_solutions_scenario_id_scenarios'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], name=op.f('fk_scenario_solutions_solution_id_solutions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_solutions'))
    )
    op.create_index(op.f('ix_scenario_solutions_scenario_id'), 'scenario_solutions', ['scenario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenario_solutions_scenario_id'), table_name='scenario_solutions')
    op.drop_table('scenario_solutions')
    op.drop_index(op.f('ix_project_solutions_solution_id'), table_name='project_solutions')
    op.drop_index(op.f('ix_project_solutions_project_id'), table_name='project_solutions')
    op.drop_table('project_solutions')
    op.drop_index(op.f('ix_solutions_vendor_id'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_status'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_solution_type_id'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_industry'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_catalog_id'), table_name='solutions')
    op.drop_table('solutions')
    op.drop_index(op.f('ix_simulation_runs_scenario_id'), table_name='simulation_runs')
    op.drop_table('simulation_runs')
    op.drop_index(op.f('ix_calculations_scenario_id'), table_name='calculations')
    op.drop_table('calculations')
    op.drop_index(op.f('ix_solution_types_process_id'), table_name='solution_types')
    op.drop_table('solution_types')
    op.drop_index(op.f('ix_scenarios_project_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_parameters_object_type_id'), table_name='parameters')
    op.drop_index(op.f('ix_parameters_group_id'), table_name='parameters')
    op.drop_table('parameters')
    op.drop_table('catalog_versions')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_object_type_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_processes_object_type_id'), table_name='processes')
    op.drop_table('processes')
    op.drop_index(op.f('ix_parameter_groups_object_type_id'), table_name='parameter_groups')
    op.drop_table('parameter_groups')
    op.drop_index(op.f('ix_import_batches_kind'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_object_types_code'), table_name='object_types')
    op.drop_table('object_types')
    op.drop_index(op.f('ix_normatives_code'), table_name='normatives')
    op.drop_table('normatives')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
